Repository neuronsimulator/nrn, pull requests merged in 2019-12, with the labels that each got.

#358 remove using-directive to cleanse global namespace from std. issue #345
  src/gnu/Complex.cpp
  src/gnu/Complex.h
  src/gnu/SmplHist.cpp
  src/gnu/SmplHist.h
  src/gnu/SmplStat.cpp
  src/ivoc/graph.h
  src/ivoc/ocglyph.h
  src/ivoc/scenevie.h
  src/ivos/ivstream.h
  src/ivos/regexp.cpp
  src/nrniv/nrnbbcore_write.cpp
  src/nrniv/nrnhash.h
  src/nrniv/nrnmenu.cpp
  src/nrniv/nrnmenu.h
  src/nrniv/partrans.cpp
  src/nrniv/shape.h
  src/nrniv/shapeplt.h
  src/parallel/bbslocal.cpp
  src/parallel/bbslsrv.cpp
Labels: enhancement

#356 Remove old/out-dated travis scripts
  .travis.yml
  .travis/format_change.sh
  .travis/install_dependencies.sh
  .travis/install_neuron.sh
  .travis/modules.yaml
  .travis/packages.linux.yaml
  .travis/packages.osx.yaml
  .travis/setup_spack.sh
  .travis_build.sh
Labels: CI, improvement

#364 Update contribution guide with cmake-format instructions
  CONTRIBUTING.md
Labels: documentation

#370 Upate travis CI to build with gcc 5.0, 6, 8 and 9 on linux platform
  .travis.yml
Labels: CI

#375 Remove hardcoded name of curses library
  src/readline/CMakeLists.txt
Labels: bug, build system
