Repository neuronsimulator/nrn, pull requests merged in 2021-08, with the labels that each got.

#1286 Remove reference to Bluegene
  docs/hoc/modelspec/programmatic/network/parcon.rst
  docs/python/modelspec/programmatic/network/parcon.rst
  docs/removed_features.rst
  src/ivoc/nrnmain.cpp
  src/nrnoc/nrntimeout.cpp
  src/oc/math.cpp
  src/oc/nrnmpiuse.h.in
  src/oc/symbol.cpp
  src/parallel/ocbbs.cpp
Labels: refactoring

#1417 debugging hints
  CMakeLists.txt
  docs/install/debug.md
  docs/install/developer.rst
Labels: documentation

#1422 bugfix: fixes a memory leak when extracellular volume fraction is changed.
  src/nrnpython/grids.cpp
Labels: bug, rxd

#1432 Remove neuron_gnu_builtin, SmplHist, SmplStat
  cmake/NeuronFileLists.cmake
  src/gnu/Binomial.cpp
  src/gnu/DiscUnif.cpp
  src/gnu/Erlang.cpp
  src/gnu/Geom.cpp
  src/gnu/HypGeom.cpp
  src/gnu/LogNorm.cpp
  src/gnu/NegExp.cpp
  src/gnu/Normal.cpp
  src/gnu/Poisson.cpp
  src/gnu/RNG.cpp
  src/gnu/SmplHist.cpp
  src/gnu/SmplHist.h
  src/gnu/SmplStat.cpp
  src/gnu/SmplStat.h
  src/gnu/Uniform.cpp
  src/gnu/Weibull.cpp
  src/gnu/builtin.cpp
  src/gnu/d_vec.cpp
  src/gnu/neuron_gnu_builtin.h
  src/gnu/neuron_gnu_std.h
  src/ivoc/ivocvect.cpp
Labels: refactoring

#1431 Remove complex
  cmake/NeuronFileLists.cmake
  src/gnu/Binomial.cpp
  src/gnu/Complex.cpp
  src/gnu/Complex.h
  src/gnu/DiscUnif.cpp
  src/gnu/Erlang.cpp
  src/gnu/Geom.cpp
  src/gnu/HypGeom.cpp
  src/gnu/LogNorm.cpp
  src/gnu/NegExp.cpp
  src/gnu/Normal.cpp
  src/gnu/Poisson.cpp
  src/gnu/RNG.cpp
  src/gnu/SmplHist.cpp
  src/gnu/SmplHist.h
  src/gnu/SmplStat.cpp
  src/gnu/SmplStat.h
  src/gnu/Uniform.cpp
  src/gnu/Weibull.cpp
  src/gnu/builtin.cpp
  src/gnu/d_vec.cpp
  src/gnu/neuron_gnu_builtin.h
  src/gnu/neuron_gnu_std.h
  src/ivoc/ivocvect.cpp
  src/nrniv/impedanc.cpp
Labels: refactoring
