Repository neuronsimulator/nrn, pull requests merged in 2023-06, with the labels that each got.

#2372 Fix compilation on Debian stable
  test/unit_tests/container/container.cpp
Labels: improvement, building, dev

#2393 replace setpointer with assignment
  docs/python/modelspec/programmatic/mechanisms/nmodl.rst
Labels: documentation

#2369 For adding only nodes to nodelist. Please check before merging.
  share/lib/python/neuron/rxd/nodelist.py
  test/rxd/test_nodelist.py
Labels: rxd

#2409 fixed a "click here" that needed a link
  docs/guide/units.rst
  docs/python/modelspec/programmatic/mechanisms/nmodl.rst
Labels: documentation
